### ISSUE TITLE
[PropertyAnimatorExample] I do not see anything in Playground's live view

### ISSUE THREAD

**Issue by Blackjacx** [shinobicontrols/iOS10-day-by-day#16]
When I open the playground and open the assistant editor, I don't see the view in the property animator. Any suggestions?

**Comment by samburnstone** [comment]
Hi,

Is the playground definitely being run? You can manually force it to execute by hitting the play button that's positioned towards the bottom of the screen.

However, it's likely that you may need to switch the Assistant Editor to 'Timeline'

![screen shot 2016-12-07 at 13 01 37](https://cloud.githubusercontent.com/assets/396605/20968761/ddff2846-bc7d-11e6-9199-8851cac85838.png)

Any luck after trying that?

**Comment by Blackjacx** [comment]
Ahhhh hitting this tiny small run button in the lower left did the trick.
My playgrounds run automatically. Strange... But thanks for the tip!

Mit freundlichen Grüßen

Stefan Herold

Mobile Software Engineer a.d. 2009

Mobil +49 175 - 19 55 3 77 <+491751955377>

E-Mail stefan.herold@gmail.com

Web www.stefan-herold.net

**Comment by samburnstone** [comment]
Ah, I often turn off the auto-execution as my laptop is a bit slow these days.

I'll enable it just in case others are having the same problem.

Thanks for bringing it up 👍
